# A Docker Compose file to set up a dev environment (not for production)
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - backend
    
  website:
    image: nginx-frontend
    build:
      context:
        ./website
      args:
      - REACT_APP_SERVICES_HOST=/services/m
    ports:
      - "80:80"
    networks:
      - backend
      - frontend

  api:
    image: nginx-backend
    depends_on:
      - db
    build:
      context: ./api
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
  frontend: