services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hutchi
      POSTGRES_DB: dogs
      POSTGRES_PASSWORD: ILoveDog$
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: