#!/usr/bin/env bash
set -e

source /run/secrets/pg_env

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER api_user WITH ENCRYPTED PASSWORD '$(echo "$API_USER_PASSWORD")';
	GRANT ALL PRIVILEGES ON DATABASE dogs TO api_user;
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO api_user;
	GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO api_user;
	GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO api_user;
EOSQL
